// Canonical project content. Used to seed an empty database (api/index.js) and
// to push updated descriptions into an already-seeded one (scripts/push-descriptions.js).
//
// longdesc_* uses a flat "## Heading" convention so the existing single TEXT
// column and the existing admin textarea keep working; App.tsx splits on it to
// render the sections.

export const seedProjects = [
  {
    title_en: "Japanese Flash Card", title_id: "Flash Card Kata Jepang",
    description_en: "Interactive quiz to drill Japanese vocabulary with audio",
    description_id: "Kuis interaktif untuk melatih kosakata Jepang lengkap dengan audio",
    longdesc_en: `## Summary
An interactive quiz web app for drilling Japanese vocabulary and kana, where every card carries native audio.

## Problem It Solves
Memorising Japanese words rarely sticks when you only ever read them — pronunciation has to be heard to be retained. Most flashcard tools are text-only, and they expect every single card to be typed in by hand, which makes building a large deck tedious enough that most people give up.

## Key Features
- Two quiz directions: Japanese to Indonesian, and Indonesian to Japanese
- Four multiple-choice options generated fresh each round from the active deck
- Audio pronunciation on every card, with a mute toggle remembered via localStorage
- Three lives and a +10 score per correct answer, with a game-over and restart flow
- A shuffled card pool that refills automatically, so no card repeats within a cycle

## Tech Stack
Vanilla JavaScript (ES modules), Vite, HTML and CSS. Deck data is generated by a Node build script. Deployed on Netlify.

## How It Works
A build script scans the audio folder and parses each filename written in the "Word【reading】.mp3" format, matches the entry against an Indonesian dictionary, and emits a flashcard data module. At runtime the app shuffles that deck, draws a card, generates one correct answer plus three distractors, plays the pronunciation, then scores the response and advances — until the three lives run out.`,
    longdesc_id: `## Ringkasan
Aplikasi web kuis interaktif untuk melatih kosakata dan kana Jepang, di mana setiap kartu dilengkapi audio pengucapan asli.

## Masalah yang Diselesaikan
Menghafal kata Jepang jarang bertahan lama kalau hanya dibaca — pengucapan perlu didengar agar benar-benar melekat. Kebanyakan aplikasi flashcard hanya berupa teks, dan mengharuskan setiap kartu diketik manual satu per satu, sehingga membangun deck besar terasa melelahkan dan biasanya ditinggalkan di tengah jalan.

## Fitur Utama
- Dua arah kuis: Jepang ke Indonesia, dan Indonesia ke Jepang
- Empat pilihan ganda yang dibuat ulang setiap ronde dari deck yang aktif
- Audio pengucapan di setiap kartu, dengan tombol mute yang tersimpan di localStorage
- Tiga nyawa dan skor +10 untuk tiap jawaban benar, lengkap dengan layar game over dan restart
- Pool kartu teracak yang otomatis terisi ulang, sehingga tidak ada kartu berulang dalam satu siklus

## Tech Stack
Vanilla JavaScript (ES modules), Vite, HTML dan CSS. Data deck dihasilkan lewat script build Node. Di-deploy di Netlify.

## Alur Kerja
Script build memindai folder audio dan membaca setiap nama file berformat "Kata【bacaan】.mp3", mencocokkannya dengan kamus bahasa Indonesia, lalu menghasilkan modul data flashcard. Saat dijalankan, aplikasi mengacak deck tersebut, mengambil satu kartu, membuat satu jawaban benar dan tiga pengecoh, memutar audionya, lalu menilai jawaban dan lanjut ke ronde berikutnya — sampai tiga nyawa habis.`,
    image: "/images/flashcard.png", link: "https://flascard-japan.netlify.app",
    tags: ["Vanilla JS", "Vite", "Web App"], category: "Education Tech"
  },
  {
    title_en: "Money Manager", title_id: "Money Manager",
    description_en: "Personal finance dashboard with cash flow insights",
    description_id: "Dashboard finansial pribadi untuk memantau arus kas dengan visualisasi data yang informatif",
    longdesc_en: `## Summary
A personal finance dashboard that tracks income and expenses, visualises cash flow, and follows progress toward savings goals.

## Problem It Solves
Spreadsheets tell you what you spent but not where the money actually goes, and they make month-to-month comparison manual work. Savings goals fare worse — without a running view of target versus current amount and time left, a goal is just a number you wrote down once and stopped looking at.

## Key Features
- Full transaction records with type, payment method, category, date, and budget month
- Cash flow and category breakdowns rendered as interactive charts
- Savings targets that track current amount against a target and a deadline
- Report export to PDF straight from the browser
- Token-based authentication with login, logout, and password change
- Per-user preferences persisted through a dedicated endpoint

## Tech Stack
Backend: Laravel REST API with Sanctum authentication, on PostgreSQL 16. Frontend: React 19, Vite, Tailwind CSS 4, Recharts for charts, jsPDF with AutoTable for exports, Axios, React Router, and Framer Motion. The whole stack runs from a single Docker Compose file.

## How It Works
The React client authenticates against the Laravel API and receives a Sanctum token, which it attaches to every later request. Transactions and savings targets are exposed as REST resources scoped to the signed-in user; the dashboard aggregates them client-side into charts, and the same data feeds the jsPDF export. Docker Compose brings up Postgres, waits for its health check, then runs migrations before serving the API.`,
    longdesc_id: `## Ringkasan
Dashboard keuangan pribadi untuk mencatat pemasukan dan pengeluaran, memvisualisasikan arus kas, serta memantau progres target tabungan.

## Masalah yang Diselesaikan
Spreadsheet bisa memberi tahu berapa yang kamu belanjakan, tetapi bukan ke mana sebenarnya uang itu pergi, dan membandingkan antar bulan harus dikerjakan manual. Target tabungan lebih parah lagi — tanpa tampilan berjalan antara target, jumlah terkumpul, dan sisa waktu, sebuah target hanya jadi angka yang ditulis sekali lalu tidak pernah dilihat lagi.

## Fitur Utama
- Pencatatan transaksi lengkap dengan tipe, metode pembayaran, kategori, tanggal, dan bulan anggaran
- Rincian arus kas dan kategori yang ditampilkan sebagai grafik interaktif
- Target tabungan yang memantau jumlah terkumpul terhadap target dan tenggat waktu
- Ekspor laporan ke PDF langsung dari browser
- Autentikasi berbasis token dengan login, logout, dan ganti kata sandi
- Preferensi per pengguna yang disimpan melalui endpoint tersendiri

## Tech Stack
Backend: REST API Laravel dengan autentikasi Sanctum, di atas PostgreSQL 16. Frontend: React 19, Vite, Tailwind CSS 4, Recharts untuk grafik, jsPDF dengan AutoTable untuk ekspor, Axios, React Router, dan Framer Motion. Seluruh stack dijalankan lewat satu file Docker Compose.

## Alur Kerja
Klien React melakukan autentikasi ke API Laravel dan menerima token Sanctum, yang kemudian disertakan di setiap permintaan berikutnya. Transaksi dan target tabungan diekspos sebagai resource REST yang dibatasi pada pengguna yang sedang login; dashboard mengolahnya di sisi klien menjadi grafik, dan data yang sama dipakai untuk ekspor jsPDF. Docker Compose menyalakan Postgres, menunggu health check-nya, lalu menjalankan migrasi sebelum melayani API.`,
    image: "/images/money-manager.jpg",
    link: "https://drive.google.com/file/d/1KJseBFLiY_8Orh4vLAk8pte81eNMvQE0/view?usp=sharing",
    tags: ["Laravel", "React", "PostgreSQL"], category: "In Progress"
  },
  {
    title_en: "IoT Waste Sorter", title_id: "IoT Pemilah Sampah",
    description_en: "ESP32-based smart metal/non-metal waste sorting",
    description_id: "Sistem cerdas berbasis ESP32 untuk memilah sampah logam dan non-logam secara otomatis",
    longdesc_en: `## Summary
A smart waste bin built around an ESP32 that detects whether an item is metal or non-metal and routes it into the correct compartment on its own.

## Problem It Solves
Waste separation depends on people getting it right at the moment they throw something away, and in shared spaces they usually do not. Once metal and non-metal end up mixed in the same bin, someone has to sort it again by hand downstream — so the separation is best handled at the point of disposal, automatically.

## Key Features
- Automatic metal versus non-metal detection through sensor input
- Motor-driven sorting mechanism that directs each item to its own compartment
- Runs unattended once powered, with no user interaction beyond dropping the item in
- WiFi-capable ESP32 platform, enabling remote monitoring of the unit

## Tech Stack
ESP32 microcontroller programmed in the Arduino/C++ environment, with detection sensors and an actuator-driven sorting mechanism.

## How It Works
An item dropped into the intake passes the sensor stage, where the ESP32 reads the signal to classify it as metal or non-metal. Based on that reading the controller drives the sorting actuator to the matching position, the item falls into the corresponding compartment, and the mechanism returns to its neutral state ready for the next item. A demo of the working unit is available on YouTube.`,
    longdesc_id: `## Ringkasan
Tempat sampah pintar berbasis ESP32 yang mendeteksi apakah sebuah benda tergolong logam atau non-logam, lalu mengarahkannya sendiri ke wadah yang sesuai.

## Masalah yang Diselesaikan
Pemilahan sampah bergantung pada ketepatan orang saat membuang, dan di ruang bersama hal itu jarang terjadi. Begitu sampah logam dan non-logam sudah tercampur dalam satu wadah, seseorang harus memilahnya ulang secara manual di tahap berikutnya — sehingga pemilahan paling tepat dilakukan otomatis, tepat di titik pembuangan.

## Fitur Utama
- Deteksi otomatis logam versus non-logam melalui pembacaan sensor
- Mekanisme pemilah berpenggerak motor yang mengarahkan tiap benda ke wadahnya sendiri
- Berjalan tanpa pengawasan begitu dinyalakan, pengguna cukup memasukkan sampahnya
- Platform ESP32 berkemampuan WiFi, membuka peluang pemantauan unit dari jarak jauh

## Tech Stack
Mikrokontroler ESP32 yang diprogram di lingkungan Arduino/C++, dengan sensor pendeteksi dan mekanisme pemilah berbasis aktuator.

## Alur Kerja
Benda yang dimasukkan ke lubang masuk melewati tahap sensor, tempat ESP32 membaca sinyal untuk mengklasifikasikannya sebagai logam atau non-logam. Berdasarkan pembacaan itu, kontroler menggerakkan aktuator pemilah ke posisi yang sesuai, benda jatuh ke wadah yang tepat, lalu mekanisme kembali ke posisi netral dan siap menerima benda berikutnya. Demo unit yang berfungsi dapat dilihat di YouTube.`,
    image: "/images/iot.png", link: "https://www.youtube.com/watch?v=x6azcS7iumg",
    tags: ["ESP32", "Arduino", "Sensors"], category: "IoT"
  },
  {
    title_en: "Sebaran Masjid Bandung", title_id: "Sebaran Masjid Bandung",
    description_en: "Mosque information portal for Bandung: map, prayer times, and statistics",
    description_id: "Portal informasi masjid Kota Bandung: peta sebaran, jadwal shalat, dan statistik",
    longdesc_en: `## Summary
An information portal covering 919 mosques across all 30 districts of Bandung, combining a distribution map, accurate prayer times, and per-district statistics in one place.

## Problem It Solves
Information about mosques in Bandung was scattered — a location on one service, prayer times on another, and no reliable picture at all of how mosques are actually distributed across the city. Anyone new to an area, or any organisation trying to plan around mosque coverage, had to piece it together from several sources.

## Key Features
- Distribution map showing mosque locations across the whole city
- Daily prayer schedule for Bandung: Subuh, Dzuhur, Ashar, Maghrib, and Isya
- Statistics broken down per district, covering 919 mosques across 30 districts
- Curated list of landmark mosques such as Salman ITB, Al-Jabbar, and Raya Bandung
- Search across the mosque directory
- Islamic study and sermon articles on the virtues of the mosque

## Tech Stack
PHP for the server-side application, with a mapping/GIS layer for the distribution view and a prayer-time calculation for the Bandung coordinates.

## How It Works
Mosque records, each tagged with its district and coordinates, are served from the database into three views of the same data: plotted individually on the map, aggregated into the per-district statistics table, and filtered through the search. The prayer schedule is computed for Bandung's location and displayed against a live clock on the homepage.`,
    longdesc_id: `## Ringkasan
Portal informasi yang mencakup 919 masjid di seluruh 30 kecamatan Kota Bandung, memadukan peta sebaran, jadwal shalat yang akurat, dan statistik per kecamatan dalam satu tempat.

## Masalah yang Diselesaikan
Informasi masjid di Bandung tersebar di mana-mana — lokasi di satu layanan, jadwal shalat di layanan lain, dan sama sekali tidak ada gambaran yang dapat diandalkan tentang bagaimana sebenarnya masjid tersebar di kota ini. Pendatang baru di suatu wilayah, atau lembaga yang ingin merencanakan sesuatu berdasarkan sebaran masjid, harus menyatukannya sendiri dari berbagai sumber.

## Fitur Utama
- Peta sebaran yang menampilkan lokasi masjid di seluruh penjuru kota
- Jadwal shalat harian untuk Bandung: Subuh, Dzuhur, Ashar, Maghrib, dan Isya
- Statistik terperinci per kecamatan, mencakup 919 masjid di 30 kecamatan
- Daftar pilihan masjid ikonik seperti Salman ITB, Al-Jabbar, dan Raya Bandung
- Pencarian di seluruh direktori masjid
- Artikel kajian dan ceramah mengenai keutamaan masjid

## Tech Stack
PHP untuk aplikasi sisi server, dengan lapisan pemetaan/GIS untuk tampilan sebaran serta perhitungan jadwal shalat berdasarkan koordinat Bandung.

## Alur Kerja
Data masjid, yang masing-masing ditandai kecamatan dan koordinatnya, disajikan dari basis data ke dalam tiga tampilan dari data yang sama: diplot satu per satu di peta, diringkas menjadi tabel statistik per kecamatan, dan disaring melalui fitur pencarian. Jadwal shalat dihitung untuk posisi Kota Bandung dan ditampilkan berdampingan dengan jam berjalan di halaman utama.`,
    image: "/images/masjid.png", link: "https://sebaran-masjid-bandung.free.je/masjid.php",
    tags: ["PHP", "GIS", "Web App"], category: "Web App"
  },
  {
    title_en: "Shiritori Zen", title_id: "Shiritori Zen",
    description_en: "Online Japanese word-chain game against a friend or the computer",
    description_id: "Game sambung kata Jepang online melawan teman atau komputer",
    longdesc_en: `## Summary
The traditional Japanese word-chain game Shiritori, rebuilt as an online game with real-time multiplayer rooms and a solo mode against the computer.

## Problem It Solves
Shiritori needs a second player and a referee — someone has to decide whether a submitted word is a real Japanese word at all. Playing it alone was impossible, and playing it online meant arguing over what counts. Validating each word against an actual dictionary settles both problems at once.

## Key Features
- Real-time multiplayer: create a room, share the room code, and play against a friend
- Solo mode against a computer opponent
- Every submitted word validated against a real Japanese dictionary, with its meaning shown
- Word history for the ongoing chain
- Animated interface with confetti on a win
- Interface written in Indonesian

## Tech Stack
Next.js 16 with the App Router and React 19, Firebase Firestore for real-time room state, Tailwind CSS 4, Framer Motion for animation, and Lucide for icons. Word validation runs through a Next.js API route backed by the Jisho dictionary API. Deployed on Vercel.

## How It Works
A player creates a room and receives a short code that a second player uses to join; both clients then subscribe to the same Firestore document, so each move appears on the other screen as it happens. When a word is submitted, the client calls an internal API route that queries the Jisho dictionary and accepts the word only on an exact match of the word or its reading, returning its meaning. The chain continues from the last character until a player fails to answer.`,
    longdesc_id: `## Ringkasan
Permainan sambung kata tradisional Jepang, Shiritori, yang dibangun ulang sebagai game online dengan ruang multiplayer real-time dan mode solo melawan komputer.

## Masalah yang Diselesaikan
Shiritori membutuhkan lawan main sekaligus wasit — harus ada yang memutuskan apakah kata yang disebut benar-benar kata Jepang. Bermain sendirian jadi mustahil, dan bermain online berujung pada perdebatan soal kata mana yang sah. Memvalidasi tiap kata ke kamus sungguhan menyelesaikan kedua masalah itu sekaligus.

## Fitur Utama
- Multiplayer real-time: buat ruang, bagikan kode ruang, lalu bermain melawan teman
- Mode solo melawan lawan komputer
- Setiap kata yang dikirim divalidasi ke kamus bahasa Jepang sungguhan, lengkap dengan artinya
- Riwayat kata untuk rantai yang sedang berjalan
- Antarmuka beranimasi dengan confetti saat menang
- Antarmuka berbahasa Indonesia

## Tech Stack
Next.js 16 dengan App Router dan React 19, Firebase Firestore untuk status ruang secara real-time, Tailwind CSS 4, Framer Motion untuk animasi, dan Lucide untuk ikon. Validasi kata berjalan lewat API route Next.js yang memanfaatkan API kamus Jisho. Di-deploy di Vercel.

## Alur Kerja
Seorang pemain membuat ruang dan mendapat kode pendek yang dipakai pemain kedua untuk bergabung; kedua klien lalu berlangganan pada dokumen Firestore yang sama, sehingga setiap langkah langsung muncul di layar lawan. Ketika sebuah kata dikirim, klien memanggil API route internal yang menanyakannya ke kamus Jisho dan hanya menerima kata itu bila cocok persis dengan tulisan atau bacaannya, sekaligus mengembalikan artinya. Rantai berlanjut dari huruf terakhir sampai ada pemain yang gagal menjawab.`,
    image: "/images/shiritorizen.png", link: "https://shiritori-zen.vercel.app/",
    tags: ["Next.js", "React", "Firebase"], category: "Gaming"
  },
  {
    title_en: "Video Tutorial Apps", title_id: "Video Tutorial Apps",
    description_en: "In-depth tutorials on my own apps' features",
    description_id: "Produksi konten tutorial mendalam mengenai penggunaan fitur-fitur aplikasi buatan saya",
    longdesc_en: `## Summary
A series of video tutorials walking through the features of the applications I have built, published on YouTube.

## Problem It Solves
A working application is not the same as an application people can actually use. Written documentation gets skipped, and a feature that takes three steps to reach is far easier to show than to describe — so the apps needed a walkthrough that shows the real interface in motion.

## Key Features
- Feature-by-feature walkthroughs recorded on the live applications
- Narration in Indonesian, aimed at first-time users
- Screen recordings that follow the actual flow a user would take
- Published openly on YouTube, linkable from each app

## Tech Stack
Screen recording and video editing, published through YouTube.

## How It Works
Each application is taken feature by feature: the flow is planned, recorded against the running app, narrated, then edited into a video that follows the same path a new user would take on their first visit.`,
    longdesc_id: `## Ringkasan
Serangkaian video tutorial yang membahas fitur-fitur aplikasi buatan saya, dipublikasikan di YouTube.

## Masalah yang Diselesaikan
Aplikasi yang berjalan tidak sama dengan aplikasi yang benar-benar bisa dipakai orang. Dokumentasi tertulis cenderung dilewati, dan fitur yang butuh tiga langkah untuk dicapai jauh lebih mudah ditunjukkan daripada dijelaskan — sehingga aplikasi-aplikasi ini memerlukan panduan yang memperlihatkan antarmuka aslinya secara langsung.

## Fitur Utama
- Panduan fitur demi fitur yang direkam langsung pada aplikasi yang berjalan
- Narasi berbahasa Indonesia, ditujukan bagi pengguna baru
- Rekaman layar yang mengikuti alur nyata yang akan ditempuh pengguna
- Dipublikasikan terbuka di YouTube dan dapat ditautkan dari tiap aplikasi

## Tech Stack
Perekaman layar dan penyuntingan video, dipublikasikan melalui YouTube.

## Alur Kerja
Setiap aplikasi dibedah fitur demi fitur: alurnya direncanakan, direkam pada aplikasi yang sedang berjalan, dinarasikan, lalu disunting menjadi video yang mengikuti jalur yang sama seperti yang ditempuh pengguna baru pada kunjungan pertamanya.`,
    image: "/images/panduan.png", link: "https://www.youtube.com/watch?v=ujRnZO3aUGU",
    tags: ["Content", "Youtube"], category: "Content"
  },
  {
    title_en: "Content Management System", title_id: "Content Management System",
    description_en: "School profile site with a full admin panel for staff",
    description_id: "Situs profil sekolah dengan panel admin lengkap untuk pengelola",
    longdesc_en: `## Summary
A school profile website whose every public page is editable by staff through an admin panel, with no developer involvement needed to publish.

## Problem It Solves
School websites go stale because updating one depends on whoever built it. An announcement that has to be relayed to a developer and waited on is an announcement that arrives late, so the people who actually hold the information need to publish it themselves.

## Key Features
- Public pages for announcements, agenda, facilities, departments, teaching staff, vision and mission, contact, and alumni
- Admin panel with full create, read, update, and delete for every one of those sections
- Image gallery per department, with individual images removable
- Session-based authentication guarding the whole admin area
- Dashboard as the entry point for administrators

## Tech Stack
Laravel with Blade templating and Eloquent models, session authentication, and PostgreSQL 16 running under Docker Compose (SQLite for local development).

## How It Works
Public routes are served by a single public controller that reads the published records straight from the database. Everything under the admin prefix sits behind session authentication, where each content type is exposed as a Laravel resource controller — so an update saved in the admin panel is reflected on the corresponding public page immediately, with no rebuild or redeploy.`,
    longdesc_id: `## Ringkasan
Situs profil sekolah yang seluruh halaman publiknya dapat disunting oleh pengelola lewat panel admin, tanpa perlu melibatkan developer untuk mempublikasikan.

## Masalah yang Diselesaikan
Situs sekolah menjadi usang karena pembaruannya bergantung pada siapa pun yang dulu membangunnya. Pengumuman yang harus diteruskan ke developer lalu ditunggu adalah pengumuman yang datang terlambat, sehingga pihak yang benar-benar memegang informasinya perlu bisa menerbitkannya sendiri.

## Fitur Utama
- Halaman publik untuk pengumuman, agenda, fasilitas, jurusan, tenaga pendidik, visi dan misi, kontak, serta alumni
- Panel admin dengan fungsi tambah, lihat, ubah, dan hapus untuk seluruh bagian tersebut
- Galeri gambar per jurusan, dengan tiap gambar dapat dihapus satuan
- Autentikasi berbasis sesi yang menjaga seluruh area admin
- Dashboard sebagai halaman masuk bagi administrator

## Tech Stack
Laravel dengan templating Blade dan model Eloquent, autentikasi sesi, serta PostgreSQL 16 yang berjalan di Docker Compose (SQLite untuk pengembangan lokal).

## Alur Kerja
Rute publik dilayani satu controller publik yang membaca data terbit langsung dari basis data. Semua yang berada di bawah prefix admin dilindungi autentikasi sesi, di mana tiap jenis konten diekspos sebagai resource controller Laravel — sehingga perubahan yang disimpan di panel admin langsung tampil di halaman publik terkait, tanpa perlu build ulang atau deploy ulang.`,
    image: "/images/content-management-system.jpg",
    link: "https://drive.google.com/file/d/1pCrtUhzFPLMoXQruTIp9Kx-NEJMWSXBo/view?usp=sharing",
    tags: ["Laravel", "Blade", "PostgreSQL"], category: "Web App"
  }
];
